env: production

replicas: 2

resources:
  cpuLimit: 500m
  memLimit: 2000Mi
  cpuRequest: 200m
  memRequest: 1500Mi
  xss: 1024m
  xmx: 1000m

configMap:
  logLevel: INFO
  baseUrl: https://api.entur.io/mobility/v2

ingress:
  enabled: true
  loadBalancerIP: 35.205.233.237
  domainName: .entur.io
