env: staging

configMap:
  logLevel: INFO
  baseUrl: https://api.staging.entur.io/mobility/v2

ingress:
  enabled: true
  loadBalancerIP: 130.211.80.129
  domainName: .staging.entur.io

lamassu:
  feedProviders:
    - systemId: YVO:System:voioslo
      systemSlug: voioslo
      operatorId: YVO:Operator:voi
      operatorName: Voi
      codespace: YVO
      url: https://api.staging.entur.io/mobility/v1/gbfs-v2_2/voioslo/gbfs
      language: nb
    - systemId: YVO:System:voitrondheim
      systemSlug: voitrondheim
      operatorId: YVO:Operator:voi
      operatorName: Voi
      codespace: YVO
      url: https://api.staging.entur.io/mobility/v1/gbfs-v2_2/voitrondheim/gbfs
      language: nb
    - systemId: YLI:System:limeoslo
      systemSlug: limeoslo
      operatorId: YLI:Operator:lime
      operatorName: Lime
      codespace: YLI
      url: https://api.staging.entur.io/mobility/v1/gbfs-v2_2/limeoslo/gbfs
      language: nb
    - systemId: YBO:System:boltoslo
      systemSlug: boltoslo
      operatorId: YBO:Operator:bolt
      operatorName: Bolt
      codespace: YBO
      url: https://api.staging.entur.io/mobility/v1/gbfs-v2_2/boltoslo/gbfs
      language: nb
    - systemId: YBO:System:boltlillestrom
      systemSlug: boltlillestrom
      operatorId: YBO:Operator:bolt
      operatorName: Bolt
      codespace: YBO
      url: https://api.staging.entur.io/mobility/v1/gbfs-v2_2/boltlillestrom/gbfs
      language: nb
    - systemId: YBO:System:boltfredrikstad
      systemSlug: boltfredrikstad
      operatorId: YBO:Operator:bolt
      operatorName: Bolt
      codespace: YBO
      url: https://api.staging.entur.io/mobility/v1/gbfs-v2_2/boltfredrikstad/gbfs
      language: nb
    - systemId: YBO:System:boltbergen
      systemSlug: boltbergen
      operatorId: YBO:Operator:bolt
      operatorName: Bolt
      codespace: YBO
      url: https://api.staging.entur.io/mobility/v1/gbfs-v2_2/boltbergen/gbfs
      language: nb
    - systemId: YOS:System:oslobysykkel
      systemSlug: oslobysykkel
      operatorId: YOS:Operator:oslobysykkel
      operatorName: Oslo bysykkel
      codespace: YOS
      url: https://api.staging.entur.io/mobility/v1/bikes/v2_2_proxy/oslobysykkel/gbfs.json
      language: nb
    - systemId: YBE:System:bergenbysykkel
      systemSlug: bergenbysykkel
      operatorId: YBE:Operator:bergenbysykkel
      operatorName: Bergen bysykkel
      codespace: YBE
      url: https://api.staging.entur.io/mobility/v1/bikes/v2_2_proxy/bergenbysykkel/gbfs.json
      language: nb
    - systemId: YTR:System:trondheimbysykkel
      systemSlug: trondheimbysykkel
      operatorId: YTR:Operator:trondheimbysykkel
      operatorName: Trondheim bysykkel
      codespace: YTR
      url: https://api.staging.entur.io/mobility/v1/bikes/v2_2_proxy/trondheimbysykkel/gbfs.json
      language: nb
    - systemId: YKO:System:kolumbusbysykkel
      systemSlug: kolumbusbysykkel
      operatorId: YKO:Operator:kolumbusbysykkel
      operatorName: Kolumbus bysykkel
      codespace: YKO
      url: https://api.staging.entur.io/mobility/v1/bikes/v2_2_proxy/kolumbusbysykkel/gbfs.json
      language: nb
    - systemId: YLS:System:lillestrombysykkel
      systemSlug: lillestrombysykkel
      operatorId: YLS:Operator:lillestrombysykkel
      operatorName: Lillestrøm bysykkel
      codespace: YLS
      url: https://api.staging.entur.io/mobility/v1/bikes/v2_2_proxy/lillestrombysykkel/gbfs.json
      language: nb
    - systemId: YDR:System:drammenbysykkel
      systemSlug: drammenbysykkel
      operatorId: YDR:Operator:drammenbysykkel
      operatorName: Drammen bysykkel
      codespace: YDR
      url: https://api.staging.entur.io/mobility/v1/bikes/v2_2_proxy/drammenbysykkel/gbfs.json
      language: nb
