env: production

replicas: 2

resources:
  cpuLimit: 500m
  memLimit: 2000Mi
  cpuRequest: 200m
  memRequest: 1500Mi
  xss: 1024m
  xmx: 1000m

configMap:
  logLevel: INFO

ingress:
  enabled: true
  productionIp: 35.205.233.237
