env: staging

resources:
  cpuLimit: 500m
  memLimit: 2000Mi
  cpuRequest: 200m
  memRequest: 1500Mi
  xss: 1024m
  xmx: 1000m

configMap:
  logLevel: INFO

ingress:
  enabled: true
  loadBalancerIP: 130.211.80.129
  domainName: .staging.entur.io
