apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
data:
  application.properties: |-
    # Spring Actuator
    management.server.port=9001
    management.endpoints.enabled-by-default=false
    management.endpoint.info.enabled=true
    management.endpoint.health.enabled=true
    management.endpoint.health.group.readiness.include=readinessState
    management.endpoint.prometheus.enabled=true
    management.endpoints.web.exposure.include=info,health,prometheus
    management.health.redis.enabled=true

    # Logging
    logging.level.no.entur.lamassu={{ .Values.configMap.logLevel }}

    # Scheduling
    org.quartz.jobStore.class=org.quartz.simpl.RAMJobStore
    spring.quartz.job-store-type=memory

    # Redis
    spring.redis.host=${REDIS_HOST}
    spring.redis.port=6379

    org.entur.lamassu.feedproviders=file:/etc/application-config/feedproviders.yml
    org.entur.lamassu.baseUrl={{ .Values.configMap.baseUrl }}

    server.error.include-stacktrace=never
  feedproviders.yml: |-
    {{- with .Values.lamassu.feedProviders }}
    lamassu:
      providers:
        {{- toYaml . | nindent 8 }}
    {{- end }}
